xen-troops/zephyr-xenlib

- xenstore-srv/src/xenstore_srv.c
A typo slipped in previous commit.
> xenstore: fix build breaking typo

- xenstore-srv/include/xss.h
- xenstore-srv/src/xenstore_srv.c
This shall allow to do XenStore clean-ups on dom0 side, e.g. vchannel server must remove its XS entries when closing connection.
> xenstore: add xss_rm() routine

- vch/include/vch.h
Specify namespace so that vch library can be used from C++ code.
> vch: enable C++ inclusion support

- xen-dom-mgmt/src/xen-dom-mgmt.c
uImage loader parses uimage_header which includes data about
image loading addresses. This is useful for the images which has
precompiled load_address.
For example: if Domain image is precompiled to boot from address
0x40080000, it can be converted to uImage using the following command:
mkimage -A arm64 -O linux -T kernel -C none -a 0x40080000 -e 0x40080000 -n "kernel" -d Image uImage
Generated uImage can be used as the Domain.
Signed-off-by: Oleksii Moisieiev <oleksii_moisieiev@epam.com>
>  xen-dom-mgmt: Add uImage loader support to boot uImages

- xen-dom-mgmt/include/xen-dom-fdt.h
- xen-dom-mgmt/src/xen-dom-fdt.c
- xen-dom-mgmt/src/xen-dom-mgmt.c
This MR includes 2 fixups:
1) Fixing build error if libfdt is not enabled
2) Fixing warning of returning value from void function
> Fixups fixing build errors and warnings in Zephyr.

- xen-dom-mgmt/include/domain.h
- xen-dom-mgmt/include/xen-dom-fdt.h
- xen-dom-mgmt/src/xen-dom-fdt.c
- xen-dom-mgmt/src/xen-dom-mgmt.c
Add dt_passthrough support to domcfg as analogue to dt_passthrough nodes in xl.cfg
This will allow us to pass nodes, that should be copied to the Domain device tree without need to put them to /passthrough node.
> Introduce dt_passthrough node support for domcfg

- Kconfig
- xen-dom-mgmt/CMakeLists.txt
- xen-dom-mgmt/include/mem-mgmt.h
- xen-dom-mgmt/src/mem-mgmt.c
- xen-dom-mgmt/src/xen-dom-mgmt.c
This patch contains implementation of several functions to simplify trivial operations for mapping, unmapping and etc memory operations for guest to Dom0. The functions help caller to avoid VLA or dynamic memory allocations as parameters for standard functions, introduce safer error handling, and try to restore memory in case of some issues.
> mem-mgmt: implement helper functions for memory management

- xenstore-srv/include/xenstore_srv.h
- xenstore-srv/src/xenstore_srv.c
This commit changes Xenstore watches logic, to prevent xenstore-srv from using global domain list during watcher notification. Referencing to domain list without proper sycnronization between xen-dom-mgmt and xenstore-srv is risky and actually was not needed.
To notify watcher domain about file changes, we need to add pending event to global pevent list and notify domain with xb_sem. Previously, watch event holded only domid, which needed a domid_to_domain() calls for notification. Now we changed domid inside this structs to domain pointers to make direct notification possible and also fixed possible watches leaks during domain destroy. In this implementation all watches and pending events will be removed during domain destroy.
> xenstore-srv: refactor watch notification to avoid domain list reference

- Kconfig
- xen-console-srv/src/xen_console.c
- xen-dom-mgmt/src/xen-dom-mgmt.c
- xenstore-srv/include/xenstore_srv.h
- xenstore-srv/src/xenstore_srv.c
Currently, DOM_MAX macro is placed in xenstore_srv.h which is confusing, because this define is used in the other not related to xenstore files. This patch converts it to Kconfig option that is more logical and additionally allows changing the maximum number of domains without changing the code.
> xen-dom-mgmt: make DOM_MAX as a config

- xen-console-srv/include/xen_console.h
- xen-console-srv/src/xen_console.c
- xen-dom-mgmt/src/xen-dom-mgmt.c
- xenstore-srv/src/xenstore_srv.c
This PR mostly fixes return code checks and adds handles to free resources in case of an error for xen-dom-mgmt. It also contains other minor fixes such as making functions static and fixing copy-paste issue.
> Fix return code checks for xen-dom-mgmt

- xrun/src/xrun.c
This MR includes 2 changes:
1) Use correct path size for kernel and dt images, received in runtime spec;
2) Use the same GIC version as on the system. It appears that Spider board do not support compatibility between GIC versions and sends not supported error when trying to start domain with gicv2 on it. That's why using system default.
> XRUN update parameters due to the integration results

- Kconfig
- xen-dom-mgmt/src/xen-dom-mgmt.c
- xen-shell-cmd/src/xen_cmds.c
PV console is actually an optional feature. It can be disabled if user is completely sure that DomUs will never use it, or if all DomUs can handle console ring buffer overrun. So, it is strictly advised to enable it, but we need to give user an ability to disable it.
Thus, make all xen_console dependencies optional, remove dependency on XEN_CONSOLE_SRV from XEN_DOMAIN_MANAGEMENT and remove "default y".
Suggested-by: Oleksandr Grytsov <oleksandr_grytsov@epam.com>
> xen_console_srv: make xen console server optional

- Kconfig
Previously, there was and error during builds for samples, that have not enable SHELL option during build. XEN_SHELL module used Zephyr shell infrastructure, but had no dependency to it. Now it will be selected in case user wants to use shell cmds for Xen domain managment.
> Kconfig: add SHELL selection for XEN_SHELL config

- xenstore-srv/src/xenstore_srv.c
The PR fixes 3 issues:
1) xss_remove behaves incorrectly in case of passing path without any child and leads to an error;
2) xss_do_write in case of memory allocation for value is failure drops the previous value;
3) If xss_do_write is failed in the node allocation loop, it doesn't free already allocated nodes;
Also, removed a redundant check that doesn't ever fire.
> Fix xss_remove and xss_do_write functions

- xen-dom-mgmt/include/domain.h
- xen-dom-mgmt/src/xen-dom-mgmt.c
- xenstore-srv/include/xenstore_srv.h
- xenstore-srv/src/xenstore_srv.c
Current implementation has a few issues such as:
1) In the case of the response buffer is overflowed due to malicious DumU (e.g. performs write operations but does not read responses), the response buffer will be corrupted because of the wrong condition. On the other hand, with the correct condition, overflowing response buffer will lead to infinite loop with trying to write zero-length data;
2) Fixed missing memory barriers in read/write operations;
3) Fixed reading/writing buffers of more than 1KB (size of ring buffers), because according to xenstore specification, it should be able to operate with buffers up to 4KB;
The PR fixes these issues.
> xenstore-srv: implement buffered read/write

- vch/src/vch.c
- xen-dom-mgmt/src/xen-dom-mgmt.c
- xenstore-srv/include/xss.h
- xenstore-srv/src/xenstore_srv.c
This PR mainly introduces of xenstore permissions feature. The feature is needed to allow or deny access between domains to process some operations with xenstore entries. In additionally to permissions support, also implemented the following:
1) Removing of entries that were created for domain or by domain in case of destruction;
2) Helper functions to create entries and set permission in one action;
3) Moved `initialize_xenstore` function to appropriate place;
4) Minor fix: /tool/xenstored was created every time on domain creation, that is not correct.
**Please note**, that the exact checking permissions were implemented in the last commit in order not to make one large commit and save code consistency between commits.
> Implement xenstore permissions

- xenstore-srv/src/xenstore_srv.c
The CONFIG_DOM_MAX mistakenly compared with domid, which are different entities. The CONFIG_DOM_MAX means the maximum running domains, domid can be any number from 0 to uint16_t. It leads to an issue when a domain can't be launched if domid is more than CONFIG_DOM_MAX, even if the number of running  domains is less than CONFIG_DOM_MAX. These incorrect checks should be removed.
> xenstore-srv: fix incorrect CONFIG_DOM_MAX checks in permissions

- xenstore-srv/src/xenstore_srv.c
The send_errno function can be invoked many times from a malicious domain for example by invoking read some xenstore file that does not exist. This will lead to spamming this error message to Dom0 console, that is not safe. Sending just error code to the caller domain is enough to signalize some error that occurred by send_reply.
> xenstore-srv: fix potential security issue while sending errno

- xen-dom-mgmt/src/mem-mgmt.c
Add stage 1 mapping after stage 2 mapping, i.e. after add to phys map. We need it because memory mapping of ext regions has been deleted from xen regions drivers and we need to perform mapping right after add to phys map.
Related pull for zephyr: https://github.com/xen-troops/zephyr/pull/56.
> xen-dom-mgmt: add ext memory regions stage 1 map and unmap

- xen-dom-mgmt/include/domain.h
- xen-dom-mgmt/src/xen-dom-fdt.c
Some device drivers require correct root node compatible during initialization process (e.g. get board revision). Previously all domain device trees contained only "xen,xenvm" compatible which is not correct.
Add possibility to configure this field via domain configuration using "machine_dt_compat" field. It will be used during domain device-tree creation.
> domain: dom-fdt: add machine-specific board compatible to domain config

- xen-dom-mgmt/src/xen-dom-fdt.c
Some of DomU may have empty or deleted passthrough node, but 'copy_node_by_path' doesn't handle it.
> xen-dom-mgmt: domU isn't able to load without passthrough node

- xen-dom-mgmt/src/xen-dom-xs.c
Enabling of CONFIG_XSTAT generated build warnings due to implicit functions and incomplete types related to xstat.
Add missing header to xen-dom-xs source file.
> xen-dom-xs: xstat: add missing xstat header to xen-dom-xs

- xen-shell-cmd/src/xenstore_cmds.c
During refactoring rename of xss_directory to xss_list_entries, one occurrence was missed. This patch fixes it.
> HOTFIX: xenstore-cmd: Fix xs_ls command

- xen-dom-mgmt/src/xen-dom-mgmt.c
- xen-dom-mgmt/src/xen-dom-xs.c
- xenstore-srv/include/xenstore_srv.h
- xenstore-srv/src/xenstore_srv.c
During Zephyr xenlib initialization some actions (root node init in Xenstore, Domain-0 Xenstore entries adding) should be done right before application start. Previously these actions were implemented in separate initcalls with different priorities which is a little bit complicated.
As we will need to have Domain-0 struct in runtime soon (for further implementation of xss watch functions in Xenstore API), Domain-0 related actions were moved to single routine: root node init was made global and xenstore entries adding was refatored. So now we can simplify priorities for initcalls and have a single place where all pre-application actions can be done.
> xen-dom-mgmt: dom0: add dom0 initcall routine

- .github/workflows/build.yaml
The workflow is triggered by push and pull request events. It uses zephyr-dom0-xt repository as a base to build zephyr-xenlib, and builds it for 4 different targets: rcar_spider, rcar_salvator_xs_m3, rcar_h3ulcb_ca57, qemu_cortex_a53.
Zephyr SDK download is cached to speed up the build process.
Example PR to see how it works: https://github.com/Deedone/zephyr-xenlib/pull/6
> CI: Add GitHub Actions workflow for building the project

- xen-dom-mgmt/src/xen-dom-mgmt.c
- xenstore-srv/src/xenstore_srv.c
Contains changes suggested in #63
> xen-dom-mgmt: improvements for dom0 initcall

- xen-console-srv/src/xen_console.c
Optimize console_display_thrd by removing the inner loop that copies data from the console buffer to the output buffer. Instead, calculate the size of the data to be copied and print it in one go.
> xen-console: Optimize console_display_thrd

- tests/xrun/CMakeLists.txt
- tests/xrun/include/domain.h
- tests/xrun/include/xen_dom_mgmt.h
- tests/xrun/include/xl_parser.h
- tests/xrun/src/mock-parser.c
- tests/xrun/src/mock-xen-dom-mgmt.c
xenlib has changed a bit and test build is broken now. This patch updates mocks to fix this.
> xrun: Fix test build

- xen-dom-mgmt/src/xen-dom-mgmt.c
- xen-shell-cmd/src/xen_cmds.c
Fixes https://github.com/xen-troops/zephyr-xenlib/issues/69
Bring command line interface of xu util to a more common form.
Make mandatory arguments positional and allow optional arguments.
Implement automatic domid selection for new domains if not provided.
Simplify console command name.
> Streamline command line interface

- Kconfig
- xen-shell-cmd/src/xenstore_cmds.c
- xenstore-srv/include/xss.h
- xenstore-srv/src/xenstore_srv.c
This series adds new Xenstore xss_list_traverse(0 API which accepts Xenstore *path* and traverse all entries recursively starting from the provided *path*. The callback provided by user is called for each Xenstore entry.
Then this xss_list_traverse() API is used to rework "xs ls" Xenstore shell command, so it can provide now proper and informative result by dumping all Xenstore entries with values recursively.
Full Xenstore dump example:
```
uart:~$ xs ls /
0: root
1:   tool
2:     xenstored = 
1:   local
2:     domain
3:       0
4:         memory
5:           static-max = 0
5:           target = 0
5:           videoram = -1
4:         control = 
5:           platform-feature-multiprocessor-suspend = 1
5:           platform-feature-xs_reset_watches = 1
5:           shutdown = 
5: …
```
> xenstore: rework "xs ls" cmd to dump all entries in a directory recursively 

- Kconfig
- xen-console-srv/src/xen_console.c
- xen-dom-mgmt/include/domain.h
- xen-dom-mgmt/src/xen-dom-mgmt.c
- xenstore-srv/include/xenstore_srv.h
- xenstore-srv/src/xenstore_srv.c
In case of Xen dom0less boot the number of guest domains could be started already by Xen before Zephyr is started. In this case it's required to follow the same approach as Xen tool init-dom0less is doing, because guest domains do not have Xenstore initialized, but do have Xenstore event and memory preallocated.
This patch adds Xen dom0less boot support in the following way:
- at init it checks for already started gest domains by using xen_domctl_getdomaininfo() for each Xen domid [1, CONFIG_DOM_MAX];
- for each found domain the Xenstore is initialized:
- use HVM_PARAM_STORE_EVTCHN to get Xenstore event
- use HVM_PARAM_MAGIC_BASE_PFN to get GFN of XEN_MAGIC pages
- setup Xenstore
- use HVM_PARAM_STORE_PFN to set Xenstore for guest domain
- trigger Xenstore event
The Xen dom0less boot …
> xen-dom-mgmt: add xen dom0less boot support

- xen-dom-mgmt/src/xen-dom-xs.c
- xenstore-srv/src/xenstore_srv.c
Some problems were found when we tried to start 2 Linux domains connected with PV drivers. Xenstore configurations sometimes came into incorrect state and produce permissions errors. Patches in this PR fixes these problems.
> Fixes for Xenstore permission related issues

- Kconfig
- vch/include/vch.h
- xen-console-srv/src/xen_console.c
- xen-dom-mgmt/src/xen-dom-mgmt.c
- xenstore-srv/include/xss.h
Set of misc, not critical updates and fixes.
> Xenlib misc updates and fixes

- xen-console-srv/src/xen_console.c
Both xen_stop_domain_console and console thread are trying to acquire global_console_lock and unset current_console at the same time. This can prevent console thread from ever stopping if xen_stop_domain_console acquires the lock first.
This patch fixes the issue by unlocking the global_console_lock before joining the console thread, and leaving the job of unsetting the current console to the console thread.
> xen_console: Fix deadlock in xen_stop_domain_console()

- xen-dom-mgmt/include/xen_dom_mgmt.h
- xen-dom-mgmt/src/xen-dom-mgmt.c
- xen-shell-cmd/src/xen_cmds.c
Currently, when domid auto allocation is used, we pass 0 to domain_post_create, causing it to fail. Fix this by returning the allocated domid from domain_create and passing it to domain_post_create.
> xen-dom-mgmt: Use correct domid for domain_post_create

- xen-dom-mgmt/include/domain.h
- xen-dom-mgmt/src/xen-dom-mgmt.c
- xen-shell-cmd/src/xen_cmds.c
Some hacky logic were added previously on domain creation - only Domain-D is unpaused after domain_create(). This looks like hack, that definitely should be removed from mainline library.
> xen-dom-mgmt: do not left domain paused on creation

- Kconfig
- xen-dom-mgmt/include/domain.h
- xen-shell-cmd/src/xen_cmds.c
- xrun/Kconfig
- xrun/src/storage.c
This series is prerequisite to enable FATFS storage on SDMMC for zephyr-dom0-xt application, instead of default littlefs.
It fixes build failure when littlefs is not enabled.
It adds support for DMA debounce buffer in xrun/storage which is required to enable DMA for SDMMC device, because xenlib loads Kernel image directly in foreign guest domain memory which can be used with DMA.
It adds  option to read domain partial device-tree binary from storage with "xu create" shell command.
> Xenlib update to support fatfs on sdmmc

- xen-dom-mgmt/src/xen-dom-mgmt.c
- xen-shell-cmd/src/xen_cmds.c
The intention of this PR is to update update domain mgmt cmds logs, so `xu create/pause/unpause/destroy` always produce some log output (on success and on failure), so it can be used by automatic tests like pytest.
On success log output looks like
`domain:%u created|destroyed|paused|unpaused`
> Xenlib update domain mgmt cmds logs

- README.md
- xen-dom-mgmt/include/domain.h
- xen-dom-mgmt/src/xen-dom-mgmt.c
The XSM policy is completely user defined, and any IDs associated with policy elements (like user, role and type) are auto-generated. The pretty complex Xen tools are responsible for converting from string "seclabel" (xl.cfg) into SSID used by Xen.
For example, below conversion happens with XSM security label, specified in xl.cfg (very simplified):
seclabel='system_u:system_r:domU_t' => domU => SECINITSID_DOMU => 12
As result, the only available option right now is to allow user to specify domain SSID in struct xen_domain_cfg.
This patch adds possibility to specify XSM security labels id for domain in struct xen_domain_cfg, which than is passed to Xen unchanged during domain creation.
> xen-dom-mgmt: add domains xsm security labels id cfg

- xrun/src/xrun.c
On the latest version of the domain_create call it's work behavoiur was changed to return domid instead of 0 if operation was succeeded. Also, domain is started automatically so update xrun_run call to match the new device_create call revision.
> xrun: update xrun_run to work with new behaviour of domain_create

- xrun/Kconfig
- xrun/src/storage.c
This PR fixes:
- xrun: storage: fix xrun_file_read_debounce() to return read bytes
- CONFIG_XRUN_STORAGE_DMA_DEBOUNCE default value to be set only for RPI5.
> xrun: storage: fix xrun_file_read_debounce() to return read bytes

- xen-dom-mgmt/include/domain.h
- xen-dom-mgmt/include/xen_dom_mgmt.h
- xen-dom-mgmt/src/xen-dom-mgmt.c
- xen-shell-cmd/src/xen_cmds.c
- xen-shell-cmd/src/xstat_cmds.c
Add the ability to use domain name instead of domid in the xu shell
commands. If the passed identifier is all numbers, then it is
considered as domid, otherwise, it is considered as domain name.
Updated commands description to reflect this change.
Also add the command to list domain infos so we can actually know the domain names.
Fixes https://github.com/xen-troops/zephyr-xenlib/issues/71
> Allow to use domain name instead of domid in commands

- tests/xrun/include/domain.h
- xen-console-srv/src/xen_console.c
- xen-dom-mgmt/include/domain.h
- xen-dom-mgmt/include/xen-dom-xs.h
- xen-dom-mgmt/src/xen-dom-mgmt.c
- xen-dom-mgmt/src/xen-dom-xs.c
- xen-shell-cmd/src/xen_cmds.c
Add refcounting to the domain structure to make it thread-safe. Fix possible deadlock in console deinit.
> xen-dom-mgmt: Fix potential concurrency issues

- xrun/src/xrun.c
Add reference counting to container objects to prevent unexpected failures when container object is freed right after return from get_container function.
Add locking to pause/resume functions.
> xrun: Fix potential concurrency issues

- vch/include/vch.h
- vch/src/vch.c
Zephyr grant table driver used incorrect structure for grant entries unmapping. Recently it was fixed and now causes warnings during build of vchan related code, since it was developed according to previous functions signatures.
Rework vchan to use correct 'struct gnttab_unmap_grant_ref' for grant entries unmapping procedures. Since this structure uses grant handles instead of gref, add such member it to vch_handle struct.
> vch: use correct structure for grant unmapping
